apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template: ## configuration about of pod
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: carmahe00/auth
        env:
          - name: JWT_KEY # value to access inside app
            valueFrom:
              secretKeyRef:
                key: JWT_KEY
                name: jwt-secret
          - name: MONGO_URI # value to access inside app
            value: 'mongodb://auth-mongo-srv:27017/auth'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - port: 3000
    targetPort: 3000
    name: auth
    protocol: TCP