apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template: ## configuration about of pod
    metadata:
      labels:
        app: expiration
    spec:
      containers:
      - name: expiration
        image: carmahe00/expiration
        env:
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: 'ticketing'
          - name: REDIS_HOST
            value: 'expiration-redis-srv'