apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template: ## configuration about of pod
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: carmahe00/payments
        env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: JWT_KEY # value to access inside app
            valueFrom:
              secretKeyRef:
                key: JWT_KEY
                name: jwt-secret
          - name: MONGO_URI # value to access inside app
            value: 'mongodb://payments-mongo-srv:27017/payments'
          - name: STRIPE_KEY # value to access inside app
            valueFrom:
              secretKeyRef:
                key: STRIPE_KEY
                name: stripe-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
  - port: 3000
    targetPort: 3000
    name: payments
    protocol: TCP